### PR TITLE
feat: passport-based authentication

### PR DESCRIPTION
**Pull request by Thegaram**
Initial implementation of passport-based authentication for evaluation (mentioned in #12).

Question: I suppose we have to use redirects (for OAuth). What's the right way of preserving our redux state in that case?

### CODE REVIEW

**Comment by Thegaram** [comment]
Login credentials are 'test'/'test' for now.

**Comment by madbence** [comment]
there is a [pure js solution for google](https://github.com/madbence/spacegame/commit/92979ef55461a25fc5db4731cf0c44e591a3dd2e) (and afaik there is one for fb too). redux: i guess it's not that bad ux if the state is lost during login (the state contains nothing useful on that page)

**Comment by Thegaram** [comment]
I like passport because it requires basically the same approach for local, Google, Facebook, etc. auth, which might make it more maintainable. But it might be overkill.

**Comment by madbence** [comment]
I guess we can go with passport for now, it is quite convenient until you want to implement something complicated, like connecting social accounts (but that's just my experience)

**Pull request closed without merging**
