### PR TITLE
Action refactoring

### PR DESCRIPTION
**Pull request by Thegaram**
Added action creators and missing actions.

### CODE REVIEW

**Comment by Thegaram** [comment]
(Tidied up commits a bit.)

**Comment by madbence** [comment]
ty :trophy: great work!

**Comment by madbence** [comment]
@Thegaram i've added you as collaborator, feel free to improve the project :smiley_cat: just stick with the pr-based workflow

**Comment by Thegaram** [comment]
Thanks! :)

**Pull request merged**
